### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by GitMensch**
adding license to the repository (Apache 2 as noted in src/main/ressources/license.html)

### CODE REVIEW

**Comment by ipolevoy** [comment]
did you know, that the license can be pulled from the Help menu? 
selection_000460

**Comment by GitMensch** [comment]
Yes, this is about adding the license as an attribute to the repository (the most obvious change if this is merged to master is that you will see the applying license in the upper right corner of the repository view). GitHub only allows to set the license property this way.

**Comment by ipolevoy** [comment]
good to know, thanks

**Comment by ipolevoy** [comment]
Pull request merged, but I do not see anything interesting in the right upper corner, can you make a screenshot?

**Comment by GitMensch** [comment]
The upper right corner just says what you can query in the repo attributes through the github api. And yes, it is set now, see:

grafik

**Comment by ipolevoy** [comment]
ah, I see it now, thanks

**Pull request merged**
