### PR TITLE
Converts '.' to '/' to use java imports by simple copy/paste

### PR DESCRIPTION
**Pull request by based2**

### CODE REVIEW

**Comment by ipolevoy** [comment]
@based2 thanks for PL. 

However, what if someone types `myimage.gif`. Your code will convert it to:  `myimage/gif` and will not find the file:)

**Comment by based2** [comment]
well, that was a short workaround. I may check that another day.

**Comment by ipolevoy** [comment]
@based2 are you going to send another commit into this PL? If so, I  will keep it.

**Comment by ipolevoy** [comment]
superseded by: https://github.com/javalite/jar-explorer/pull/3

**Pull request closed without merging**
